### ISSUE TITLE
Salvage scripts from Dimi and setup repo like we do for TrIAS

### ISSUE THREAD

**Issue by peterdesmet** [inbo/rl-flanders-checklist#1]
I have copied all work done by @DimEvil from:

https://github.com/inbo/data-publication/tree/master/datasets/rl-flanders-unvalidated-checklist
https://github.com/inbo/data-publication/tree/master/datasets/rl-flanders-validated-checklist

... to this branch: https://github.com/inbo/red-list-flanders-checklist/tree/copy-info

I tried to organize it following data science cookie cutter, removing duplicate files. Because R, Notebooks, Exploratory and Refine was used, we still have a lot of scripts and interim data files in that branch, so best not to merge.

We need to set up 2 dwc_mapping.Rmd files (for validated and unvalidated) and incorporate the good parts from the existing scripts.

**Comment by DimEvil** [comment]
Not sure we should keep all the interim data for this repo. I'd rather remove it for the moment, redo the scripts and check if there is some interim data to keep. the original repo was created 9 months ago, before a structure was even proposed.

**Comment by peterdesmet** [comment]
I agree, which is why I parked those data and scripts on a separate branch, as backup for now.
