### ISSUE TITLE
Red lists Flanders, native - not native incorrect

### ISSUE THREAD

**Issue by DimEvil** [inbo/rl-flanders-checklist#18]

**Comment by peterdesmet** [comment]
Which species?

**Comment by DimEvil** [comment]
many species, vbv 'hangbuikzwijn'

**Comment by peterdesmet** [comment]
It is mapped to `native` for all values (except for unvalidated):

https://github.com/inbo/rl-flanders-checklist/blob/bcaceef59f278b35a5045a3c9134cd4315f3505b/src/dwc_mapping_nonvalidated.Rmd#L398-L400

https://github.com/inbo/rl-flanders-checklist/blob/bcaceef59f278b35a5045a3c9134cd4315f3505b/src/dwc_mapping_validated.Rmd#L402-L407

Clearly, we shouldn't use a blanket value for all.

**Comment by peterdesmet** [comment]
@dirkmaes33 how can we make an easier assessment of which species on the list are native?

**Comment by dirkmaes33** [comment]
all species with a Red list status that equals RE, CR, EN, VU, NT, LC and DD are in principle native species. Otherwise, they would not have been assessed against Red List criteria ...

**Comment by peterdesmet** [comment]
Ok, good to know. Will update this info when I get a chance.

**Comment by peterdesmet** [comment]
For reference: https://www.gbif.org/species/152627007/verbatim should have establishmentMeans empty rather than native

**Comment by peterdesmet** [comment]
Fixed in the code and republished. Should be online in GBIF in couple of minutes.
